### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by r-barnes** [AlbertHZL/PIS-G#1]
Could you please edit the README to explain how to use the software to reproduce the results in the paper?

**Comment by AlbertHZL** [comment]
Thanks for this comment! We have revised README, explaining how to use the software to reproduce the results in the paper. Also, the information about code dependencies and producing dlls is added to README.

**Comment by AlbertHZL** [comment]
README has been edited again to explain how to produce two dlls with CMake.

**Comment by r-barnes** [comment]
Thanks!
