### ISSUE TITLE
dll's

### ISSUE THREAD

**Issue by r-barnes** [AlbertHZL/PIS-G#3]
Please remove dlls from the repo and provide directions for the user to install the necessary software.

**Comment by AlbertHZL** [comment]
Thanks for this comment! Dlls have been removed from the folder of src. Besides, README was edited, "two dlls are needed, produced by 'Forwarding_DLL.h' and 'Forwarding_DLL.cpp', 'grav_rfi_ompcuda.h' and 'grav_rfi_ompcuda.cu', respectively” is mentioned in README. "cudart64_102.dll" is a dynamic link library of CUDA, which is necessary when running the executable file of PIS-G. So "cudart64_102.dll" is offered and located in the folder of "supplementary_files".

**Comment by r-barnes** [comment]
Thanks. I think build instructions for those DLLs should appear in the README once they're available.

Getting rid of `cudart64_102.dll` still seems important:
1. If the user has a CUDA-enabled GPU they'll have this file or its equivalent on their machine already and the system should find it when running the program.
2. This solution won't help Mac/Linux users as the DLL will be specific to the Windows platform.
3. It limits the scope of your code as some firewalls will reject the DLL since it could contain malicious code (no way to verify its provenance).

If the system isn't identifying the correct library at run-time, then thinking about the build system or dynamic library identification is probably the right solution. Or, put another way, I've never seen a situation where including the DLL was necessary and it's unlikely this is the exception.

 Also, relying on this specific version (10.2) also risks future incompatibility as new GPUs emerge.

**Comment by AlbertHZL** [comment]
Thanks for this comment! cudart64_102.dll has been deleted. It was added in case that the user could run PIS-G executable program without installing CUDA. Now it is removed as you commented. Thanks!

**Comment by r-barnes** [comment]
Thanks!
