### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by r-barnes** [AlbertHZL/PIS-G#4]
Please include a [requirements file](https://pip.pypa.io/en/stable/user_guide/#requirements-files) to help users automatically install your code's dependencies.

**Comment by AlbertHZL** [comment]
Thanks for this comment! We have added a requirement file.

**Comment by r-barnes** [comment]
Thanks, that looks pretty good. I have two additional comments here:

1. Ideally the file (and all files) ends with a new line. Right now there is no `\n` after "PyQt5-tools==5.13.0.1.5".
2. Pinning your code to exact versions guarantees compatibility with a known environment, but you should with high probability be able to use compatible versions (see [this link](https://stackoverflow.com/questions/39590187/in-requirements-txt-what-does-tilde-equals-mean)), at least if [semantic versioning](https://semver.org/) is being used by the package.

You can choose to consider or ignore this last point.

**Comment by AlbertHZL** [comment]
Thanks for this comment! We have revised it as suggested.

**Comment by r-barnes** [comment]
Thanks!
