### ISSUE TITLE
cmake

### ISSUE THREAD

**Issue by r-barnes** [AlbertHZL/PIS-G#5]
Since your code includes C++ source code, a build file of some sort is needed.

I recommend using the cmake system as it seems to provide an easy interface that exposes a lot of power. [See this](https://github.com/jtebert/kilosim/blob/master/CMakeLists.txt) for an example. Do let me know if you need help.

**Comment by AlbertHZL** [comment]
Thanks for this comment! We have finished CMakeLists.txt for producing Forwarding_DLL.dll. But we have some problems when we build a cmake file for grav_rfi_ompcuda.dll. Only after the solution generated by cmake is further configured in Visual Studio, grav_rfi_ompcuda.dll could be produced. So it will take us a few days to finish that (maybe just one day or less time). Two cmake files will be uploaded as soon as dlls are built successfully.

**Comment by r-barnes** [comment]
Thanks for looking into this.

[This page](https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html#id13) has a list of generators supported by cmake. Taking a look at [one of them](https://cmake.org/cmake/help/latest/generator/Visual%20Studio%2016%202019.html) shows that you can use cmake to generate a C++ project like so:
```
cmake -G "Visual Studio 16 2019"
```
You then use cmake by navigating to the root directory of the project and running the following:
```
mkdir build
cd build
cmake -G "Visual Studio 16 2019" ..
make
```
(or at least you would in a shell, I'm not sure how you go about doing this on Windows).

If you don't have access to a Linux box, I can put in a PR for any changes needed to make `cmake` work on a Linux system.

**Comment by AlbertHZL** [comment]
Thanks for this comment! After days' work, a CMakeLists.txt is uploaded to the repository of PIS-G, used for producing two important dlls. Thank you very much! We learned much from the work. The README.md is also updated to explain how to produce dlls with CMakeLists.txt.

**Comment by r-barnes** [comment]
I've submitted a PR #8 that cleans the cmake file somewhat and makes some other minor edits so code compiles on my machine. Could you see if it still works on your end?

**Comment by AlbertHZL** [comment]
Thanks for your contributions very much! But the revised codes could not be built successfully. We edited them again and now they could compile on our computer. You can find the minor changes where the comments are added . If there is no problem in the codes, I'll merge PR.

**Comment by AlbertHZL** [comment]
After merging PR, README.md is also revised for cmake. Thanks!

**Comment by AlbertHZL** [comment]
I think this issue could be closed now. If any question, contact me, thanks.

**Comment by r-barnes** [comment]
I agree, thank you.
