### ISSUE TITLE
Remove comment artefacts

### ISSUE THREAD

**Issue by r-barnes** [AlbertHZL/PIS-G#6]
Commented-out code [like this](https://github.com/AlbertHZL/PIS-G/blob/master/Source%20codes/MatplotlibWidget.py#L18-L19) is confusing to people who might build off of your work. Please remove such code wherever possible, or place it within clearly-documented if-statements.

**Comment by AlbertHZL** [comment]
Thanks for this comment! The commented-out codes were removed.

**Comment by r-barnes** [comment]
That looks much cleaner, thank you.
