### ISSUE TITLE
Avoid catch-all excepts

### ISSUE THREAD

**Issue by r-barnes** [AlbertHZL/PIS-G#7]
Catch-all excepts like [this one](https://github.com/AlbertHZL/PIS-G/blob/96f7ba2873d0a9b923e41af56ce1e1daf87b1aa4/Source%20codes/MainWindow.py#L182) prevent issues from reaching a user and can hide unexpected conditions. Please make your expects pertain to a specific problem, e.g. `except ValueError as err`

**Comment by AlbertHZL** [comment]
Thanks for this comment! We have revised them. For the details, see the source codes, please.

**Comment by r-barnes** [comment]
Looks good, thanks!
